# Initially generated by GitHub Copilot.
"""Helpers for stable generation provenance breadcrumbs."""

import functools
from pathlib import Path

_SIDECAR_NAME = "provenance.md"


def generated_by_text(generator_file: str, repo_name: str | None = None) -> str:
    """Return a stable human-readable generated-by string."""
    return f"This file was generated by {_display_path(generator_file, repo_name)}."


def generated_html_comment(generator_file: str, repo_name: str | None = None) -> str:
    """Return an HTML comment payload for a generated file."""
    return f"Do not edit by hand. {generated_by_text(generator_file, repo_name)}"


def with_json_provenance(root, generator_file: str, repo_name: str | None = None):
    """Return a JSON root dict with provenance inserted as the first key."""
    if not isinstance(root, dict):
        raise TypeError("JSON provenance injection requires a top-level dict")
    rest = {key: value for key, value in root.items() if key != "provenance"}
    return {"provenance": generated_by_text(generator_file, repo_name), **rest}


def write_directory_provenance(
    dir_path: str,
    generator_file: str,
    artifacts_description: str,
    sidecar_name: str = _SIDECAR_NAME,
    repo_name: str | None = None,
    newline: str = "",
):
    """Write a provenance sidecar for a directory of generated artifacts."""
    out_path = Path(dir_path) / sidecar_name
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8", newline=newline) as out_fp:
        out_fp.write(
            directory_provenance_markdown(
                generator_file, artifacts_description, repo_name
            )
        )


def directory_provenance_markdown(
    generator_file: str, artifacts_description: str, repo_name: str | None = None
) -> str:
    """Return Markdown text for a directory-level provenance sidecar."""
    description = artifacts_description.rstrip(".")
    return "\n".join(
        (
            "<!-- Initially generated by GitHub Copilot. -->",
            "# Provenance",
            "",
            f"This directory contains generated {description}.",
            generated_by_text(generator_file, repo_name),
            "Payload files in this directory remain in their native data format, so provenance is recorded here rather than inside each file.",
            "",
        )
    )


def this_repo_name() -> str:
    """Name of the repo this module's checkout belongs to.

    Named ``this_repo_name`` rather than ``repo_name`` because every public function
    here already takes a ``repo_name`` parameter, which would shadow it.

    Derived by this chain, first answer wins:

    1. the common git dir -- ``repo_root/.git`` itself when that is a directory, and in
       a linked worktree the main clone's ``.git`` that the worktree's ``.git`` *file*
       points into (``_common_git_dir``);
    2. the basename of ``remote.origin.url`` in that dir's ``config``, a trailing
       ``.git`` stripped (``_origin_basename``).  This is the step that also gets a
       renamed clone directory right;
    3. the common git dir's parent name, when that dir is literally named ``.git``
       (``_clone_dir_name``) -- a clone or worktree whose config names no origin;
    4. ``repo_root.name``, which is what this used before any of the above existed.

    A WORKTREE IS THE SAME REPO, so a breadcrumb generated from one must name the repo.
    These breadcrumbs are written into git-tracked artifacts, several of which are
    compared against a fresh regeneration by the test suite; naming the worktree makes
    the same generator emit different bytes depending on which checkout ran it, which
    shows up either as a spurious test failure or -- worse -- as a real commit carrying
    a throwaway worktree name in a published file.  Found 2026-08-07, when
    MAM-simple/doc/versification-differences.md regenerated from a worktree as "generated
    by busy-chebyshev-613a3b/py/...".

    FAILURE DEGRADES, NEVER RAISES.  A malformed ``.git`` file, an unreadable config, or
    a bare or exported tree with no ``.git`` at all falls through to step 4 and so
    reproduces exactly the output of before this chain existed, rather than exploding
    several hundred generated files into a full regeneration.  (``_display_path``'s
    ``ValueError`` for a generator outside both roots is a different contract and stays.)

    Standard library only, and deliberately consulting no other module of ours: this file
    is vendored verbatim into sibling repos (al-hatorah's ``py/mb_cmn/`` among them) that
    have no ``mb_cmn/paths.py`` to import.  It reads git's own files and never shells out,
    so it does not require git on PATH.  A tree nested inside another repo's checkout --
    al-hatorah at ``MAM-private/al-hatorah`` since 2026-08-10 -- has no ``.git`` of its
    own at ``repo_root``, so it takes step 4 and is named for its directory, which is the
    right answer and is why nesting needs no override.
    """
    return _derived_repo_name(_repo_root())


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


@functools.lru_cache(maxsize=None)
def _derived_repo_name(root: Path) -> str:
    """``this_repo_name``'s chain, memoized on the resolved repo root.

    Memoized because a full ``main_0_mega.py`` run asks for a breadcrumb thousands of
    times and should read git's config once.
    """
    try:
        common_git_dir = _common_git_dir(root)
        if common_git_dir is not None:
            derived = _origin_basename(common_git_dir / "config") or _clone_dir_name(
                common_git_dir
            )
            if derived:
                return derived
    except Exception:  # Degrade to the directory name; see this_repo_name's docstring.
        pass
    return root.name


def _common_git_dir(root: Path) -> Path | None:
    """The git dir shared by ``root`` and its worktrees, or ``None``.

    ``root/.git`` is a directory in an ordinary clone and a *file* in a linked worktree,
    holding ``gitdir: <main clone>/.git/worktrees/<worktree name>``.  Which clone that
    worktree belongs to is then read from the ``commondir`` file git writes beside it
    (contents ``../..``), rather than inferred from the path.
    """
    dot_git = root / ".git"
    if dot_git.is_dir():
        return dot_git
    if not dot_git.is_file():
        return None
    gitdir = _gitdir_pointer(root, dot_git)
    if gitdir is None:
        return None
    commondir = gitdir / "commondir"
    if not commondir.is_file():
        # A submodule's .git file points at <super>/.git/modules/<name>, which has no
        # commondir: that directory is the submodule's own git dir, not a shared one.
        return gitdir
    common = Path(commondir.read_text(encoding="utf-8").strip())
    return common if common.is_absolute() else (gitdir / common).resolve()


def _gitdir_pointer(root: Path, dot_git: Path) -> Path | None:
    """The path a worktree's ``.git`` file points at, or ``None`` if it says nothing."""
    prefix = "gitdir:"
    text = dot_git.read_text(encoding="utf-8")
    line = next((ln for ln in text.splitlines() if ln.strip().startswith(prefix)), None)
    if line is None:
        return None
    gitdir = Path(line.strip()[len(prefix) :].strip())
    if gitdir.is_absolute():
        return gitdir
    # Git 2.48+ can write this relative to the worktree, with --relative-paths.
    return (root / gitdir).resolve()


def _origin_basename(config_path: Path) -> str | None:
    """Basename of ``remote.origin.url`` in a git config file, else ``None``.

    Hand-scanned rather than handed to ``configparser``, whose continuation-line
    handling of tab-indented bodies is a liability here.  The shape is a section header
    at column 0 -- ``[remote "origin"]`` -- and then a tab, ``url = <url>``.
    """
    if not config_path.is_file():
        return None
    in_origin = False
    for line in config_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("["):
            in_origin = "".join(stripped.split()) == '[remote"origin"]'
            continue
        if not in_origin:
            continue
        key, sep, value = stripped.partition("=")
        if sep and key.strip() == "url":
            return _url_basename(value.strip())
    return None


def _url_basename(url: str) -> str | None:
    """Repo name from a remote URL: its last segment, a trailing ``.git`` stripped.

    Ben's remotes are inconsistent about that suffix -- MAM-basics carries it and
    MAM-simple does not -- so stripping it is required rather than defensive.  Handles
    ``https://github.com/bdenckla/MAM-basics.git``, the scp-style
    ``git@github.com:bdenckla/MAM-basics``, and a local path in either slash.
    """
    trimmed = url.replace("\\", "/").rstrip("/")
    name = trimmed.rsplit("/", 1)[-1].rsplit(":", 1)[-1]
    if name.endswith(".git"):
        name = name[: -len(".git")]
    return name or None


def _clone_dir_name(common_git_dir: Path) -> str | None:
    """Name of the directory holding ``common_git_dir``, when it is literally ``.git``.

    Covers a clone or worktree whose config names no origin.  The guard matters: a
    submodule's git dir is ``<super>/.git/modules/<name>``, whose parent is ``modules``.
    """
    if common_git_dir.name != ".git":
        return None
    return common_git_dir.parent.name or None


def _display_path(generator_file: str, repo_name: str | None = None) -> str:
    """Repo-relative breadcrumb for ``generator_file``.

    The top-level path segment is the ``repo_name`` argument when supplied, else the
    repo's own name as ``this_repo_name()`` above resolves it.

    Nothing in MAM-basics passes ``repo_name`` any more.  It was wlc-utils'
    ``REPO_NAME`` override, which held the breadcrumbs at ``wlc-utils/...`` while
    that repo's Python was being copied into MAM-basics, and was dropped on
    2026-08-01 once the generators really did live here.
    """
    generator_path = Path(generator_file).resolve()
    repo_root = _repo_root()
    # The DIRECTORY name, which is what the path arithmetic below needs, and which in a
    # worktree is exactly what the emitted logical_name must not be.
    actual_name = repo_root.name
    logical_name = repo_name if repo_name is not None else this_repo_name()
    repos_root = repo_root.parent
    try:
        repos_rel = generator_path.relative_to(repos_root).as_posix()
        prefix = f"{actual_name}/"
        if repos_rel.startswith(prefix):
            return f"{logical_name}/{repos_rel[len(prefix):]}"
    except ValueError:
        pass
    try:
        repo_rel = generator_path.relative_to(repo_root).as_posix()
    except ValueError as exc:
        raise ValueError(
            f"Generator path is outside both {repo_root} and {repos_root}: {generator_path}"
        ) from exc
    return f"{logical_name}/{repo_rel}"
