# Initially generated by GitHub Copilot.
"""Exports gen_html_file: lists detail pages whose comments mention μY."""

from py import my_html
from pyauthor_util import author
from pyauthor_util.common_titles_etc import D6_TITLE, D6_H1_CONTENTS, D6_FNAME
from pyauthor_util.common_titles_etc import d1d_detail_href
from pyauthor_util.short_id_etc import short_id


def gen_html_file(tdm_ch, eqrs):
    author.assert_stem_eq(__file__, D6_FNAME)
    cbody = _make_cbody(eqrs)
    author.help_gen_html_file(tdm_ch, D6_FNAME, D6_TITLE, cbody)


def _make_cbody(eqrs):
    matching = [eqr for eqr in eqrs if _comments_mention_mu_y(eqr)]
    n = len(matching)
    intro = f"The following {n} details pages have a comment that mentions μY."
    items = [_list_item(eqr) for eqr in matching]
    return [
        author.heading_level_1(D6_H1_CONTENTS),
        author.para(intro),
        my_html.unordered_list(items),
    ]


def _list_item(eqr):
    sid = short_id(eqr)
    cv = eqr["qr-cv"]
    wiw = eqr["qr-what-is-weird"]
    wiw_text = _extract_text(wiw)
    link = my_html.anchor_h(f"Job {cv}", d1d_detail_href(sid))
    return [link, f" — {wiw_text}"]


def _comments_mention_mu_y(eqr):
    return _field_mentions_mu_y(eqr, "qr-generic-comment") or _field_mentions_mu_y(
        eqr, "qr-bhq-comment"
    )


def _field_mentions_mu_y(eqr, field):
    value = eqr.get(field)
    if value is None:
        return False
    return "μY" in _extract_text(value)


def _extract_text(obj):
    """Recursively extract plain text from a string, list, or htel."""
    if isinstance(obj, str):
        return obj
    if isinstance(obj, dict):
        # htel element: extract text from its contents
        contents = obj.get("contents")
        if contents is None:
            return ""
        return _extract_text(contents)
    if isinstance(obj, (list, tuple)):
        return "".join(_extract_text(item) for item in obj)
    return ""
