# Initially generated by GitHub Copilot.
"""
List quirkrecs that are missing Aleppo Codex word-crop images.

Usage:
    python main_list_missing_aleppo_imgs.py          # show first 15 missing
    python main_list_missing_aleppo_imgs.py --all     # show all missing
    python main_list_missing_aleppo_imgs.py -n 20     # show first 20 missing

A quirkrec is considered "done" if:
    - gh-pages/jobn/img/Aleppo/Aleppo-{sid}.png exists, OR
  - the quirkrec already has a 'qr-aleppo-img' key
"""

import json
import sys

import boj_paths
from pyauthor_util.short_id_etc import short_id

with open(boj_paths.enriched_quirkrecs_path(), encoding="utf-8") as _f:
    EQRS = json.load(_f)
IMG_DIR = boj_paths.aleppo_img_dir()


def get_done_and_missing():
    done = []
    missing = []
    for eqr in EQRS:
        sid = short_id(eqr)
        img_path = IMG_DIR / f"Aleppo-{sid}.png"
        has_aleppo_key = bool(eqr.get("qr-aleppo-img"))
        if img_path.exists() or has_aleppo_key:
            done.append(sid)
        else:
            cv = eqr.get("qr-cv", "?")
            consensus = eqr.get("qr-consensus", "?")
            missing.append((sid, cv, consensus))
    return done, missing


def main():
    show_all = "--all" in sys.argv

    # Parse -n <count>
    limit = None
    if "-n" in sys.argv:
        idx = sys.argv.index("-n")
        if idx + 1 < len(sys.argv):
            limit = int(sys.argv[idx + 1])
    if not show_all and limit is None:
        limit = 15

    done, missing = get_done_and_missing()

    print(f"Done: {len(done)}", end="")
    if done:
        preview = ", ".join(done[:10])
        if len(done) > 10:
            preview += ", ..."
        print(f"  ({preview})")
    else:
        print()
    print(f"Missing: {len(missing)}")
    print()

    display_count = len(missing) if show_all else min(limit, len(missing))
    for i in range(display_count):
        sid, cv, cons = missing[i]
        print(f"  {sid}  Job {cv}  {cons}")
    if display_count < len(missing):
        print(f"  ... and {len(missing) - display_count} more")


if __name__ == "__main__":
    main()
