# Initially generated by GitHub Copilot.
"""Common Cantillation of Scripture URLs used in quirk records."""

from mb_cmn.url_percent import pct_path_component

_COS_BASE_URL = "https://www.chorev.co.il/"
_COS_HEBREW_PATH = "טעמי-המקרא"
_COS_ENGLISH_PATH_SUFFIX = "באנגלית-THE-CANTILLATION-OF-SCRIPTURE"


def cos_original_url() -> str:
    return f"{_COS_BASE_URL}{pct_path_component(_COS_HEBREW_PATH)}.htm"


def cos_translation_url() -> str:
    return (
        f"{_COS_BASE_URL}"
        f"{pct_path_component(_COS_HEBREW_PATH)}"
        f"-{pct_path_component(_COS_ENGLISH_PATH_SUFFIX)}.htm"
    )
